version: "3.8"

services:
  superset_db:
    image: postgres:17
    container_name: superset_db
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - superset_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - superset_net

  superset_cache:
    image: redis:7
    container_name: superset_cache
    networks:
      - superset_net

  superset_app:
    build: .
    container_name: superset_app
    environment:
      - DATABASE_USER=superset
      - DATABASE_PASSWORD=superset
      - DATABASE_HOST=superset_db
      - DATABASE_PORT=5432
      - DATABASE_DB=superset
      - REDIS_HOST=superset_cache
      - REDIS_PORT=6379
      - SECRET_KEY=this_is_a_very_secret_key
    ports:
      - "8088:8088"
    depends_on:
      - superset_db
      - superset_cache
    networks:
      - superset_net
    command:
      >
      bash -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Admin --lastname User --email admin@admin.com --password admin &&
        superset init &&
        gunicorn -w 4 -k gevent --timeout 300 -b 0.0.0.0:8088 'superset.app:create_app()'
      "

volumes:
  superset_db_data:

networks:
  superset_net:
    driver: bridge
